version: '3.8'

services:
  immich-metadata-sync:
    image: germanlion67/immich-metadata-sync:latest
    container_name: immich-metadata-sync-test
    volumes:
      - /home/immich/immich-library/library:/library
      - ./logs:/app/logs
    # If you don't have stack.env, comment out the next line with #
    env_file:
      - stack.env
    healthcheck:
      test: ["CMD", "python", "/app/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # The Docker image already contains all dependencies and scripts
    # To run different commands, override the CMD:
    # command: ["python", "/app/immich-ultra-sync.py", "--all", "--only-new"]
